### ISSUE TITLE
Triggers setup for Trinket/Heart of Azeroth

### ISSUE THREAD

**Issue by JoshLu0614** [nebularg/Parrot2#64]
### What steps will reproduce the problem?
1.  Delete Parrot.lua and Parrot.lua.bak files in the the SavedVariables folder and disable all other addons 
2.  Open Parrot 2 addon and create a trigger for my trinket and Heart of Azeroth. For the Primary condition choose Item cooldown ready and fill in the ID. 
3.  Leave secondary condition empty
4.  Setup the style - Fill in the same ID in the Icon field, press the test button and it seems all good. The problem is notifications never showup under any circumstances. I have spent couple of hours trying to figure out the right condition but make no progress. Please kindly advise and thanks in advance.
### What version of Parrot are you using?
v2.1.9

### Do you have an error log of what happened?
No, but certainly could if I know where to lookup the error log.

### Please provide any additional information below. (example: localization of your client if not enUS or enGB)
My Wow client is zhCN but the language is English.
![HOA](https://user-images.githubusercontent.com/64176056/80048004-7de8d200-8541-11ea-8326-afcf7d231a63.JPG)
![VOA](https://user-images.githubusercontent.com/64176056/80048007-7fb29580-8541-11ea-915d-f32334ddd469.JPG)

**Comment by nebularg** [comment]
Cooldown triggers use the name instead of the ID 😛 

So for the trinket if you use the name for the condition and the icon it should work like you'd expect. For the essence, the neck itself doesn't go on cooldown, but you can instead use the "Spell ready" condition with the essence spell name.

I had to fix being able to use Azerite Essence spell names, so you'll need to update to v2.1.10 for that. Thanks!

**Comment by JoshLu0614** [comment]
The trigger for the trinket works! I really can't thank you enough for your help.
